// TU SINH tu du lieu trang on thi cu cua chu du an (Grade PTIT) - dung sua tay,
// chay lai script chuyen doi neu can cap nhat.
import type { CauHoi, DeLuyenTap } from "../practiceData";

export const DE_LUYEN_TAP: DeLuyenTap[] = [
  {
    id: "attt-1",
    monId: "mon-1",
    title: "Đề trắc nghiệm an toàn bảo mật hệ thống thông tin số 1",
    description: "Cứ ôn là A+",
    soCau: 209,
  },
  {
    id: "attt-2",
    monId: "mon-1",
    title: "Đề trắc nghiệm an toàn bảo mật hệ thống thông tin số 2",
    description: "Cứ ôn là A+",
    soCau: 297,
  },
  {
    id: "mon2-1",
    monId: "mon-2",
    title: "Công Nghệ Phần Mềm - PTIT",
    description: "",
    soCau: 178,
  },
  {
    id: "mon3-1",
    monId: "mon-3",
    title: "Đề trắc nghiệm kinh tế chính trị Mác - Lênin (HUBT)",
    description: "Cứ ôn là A+",
    soCau: 101,
  },
  {
    id: "mon3-2",
    monId: "mon-3",
    title: "Đề trắc nghiệm kinh tế chính trị Mác - Lênin số 2",
    description: "Đề tổng hợp từ  Trường Đại học Kinh doanh và Công nghệ Hà nội",
    soCau: 100,
  },
  {
    id: "mon3-3",
    monId: "mon-3",
    title: "Đề trắc nghiệm kinh tế chính trị Mác - Lênin số 3",
    description: "Cứ ôn là A+",
    soCau: 379,
  },
  {
    id: "mon3-4",
    monId: "mon-3",
    title: "Đề trắc nghiệm kinh tế chính trị Mác - Lênin số 4",
    description: "Cứ ôn là A+",
    soCau: 100,
  },
  {
    id: "mon3-5",
    monId: "mon-3",
    title: "Đề trắc nghiệm kinh tế chính trị MÁC – LÊNIN 700 câu",
    description: "Cứ ôn là A+",
    soCau: 684,
  },
  {
    id: "mon4-1",
    monId: "mon-4",
    title: "E - marketing",
    description: "",
    soCau: 146,
  },
  {
    id: "mon5-1",
    monId: "mon-5",
    title: "CSDL P1",
    description: "",
    soCau: 101,
  },
  {
    id: "mon5-2",
    monId: "mon-5",
    title: "Đề trắc nghiệm Cơ sở dữ liệu số 1",
    description: "Cứ ôn là A+",
    soCau: 250,
  },
  {
    id: "mon6-1",
    monId: "mon-6",
    title: "Thống Kê Doanh Nghiệp - PTIT 2025",
    description: "",
    soCau: 293,
  },
  {
    id: "mon7-1",
    monId: "mon-7",
    title: "Tư tưởng Hồ Chí Minh",
    description: "",
    soCau: 100,
  },
  {
    id: "mon7-2",
    monId: "mon-7",
    title: "Tư tưởng Hồ Chí Minh (PTIT) - MỚI NHẤT 2025",
    description: "",
    soCau: 253,
  },
  {
    id: "mon8-1",
    monId: "mon-8",
    title: "Toán Cao Cấp 1 (PTIT) - 2025",
    description: "",
    soCau: 30,
  },
  {
    id: "mon9-1",
    monId: "mon-9",
    title: "Trắc nghiệm Nhập môn Truyền thông",
    description: "",
    soCau: 125,
  },
  {
    id: "mon10-1",
    monId: "mon-10",
    title: "ôn tập mttq",
    description: "",
    soCau: 126,
  },
  {
    id: "mon11-1",
    monId: "mon-11",
    title: "Ôn quản trị tài chính",
    description: "",
    soCau: 90,
  },
  {
    id: "mon12-1",
    monId: "mon-12",
    title: "Trắc nghiệm Quản lý dự án - 201 câu hỏi",
    description:
      "Bộ 201 câu hỏi trắc nghiệm Quản lý dự án bao gồm 7 chương: Tổng quan về QLDA, Tổ chức bộ máy dự án, Phương pháp định lượng trong QLDA, Quản lý nguồn lực và chủ thể liên quan, Quản lý tiến độ và thời gian, Quản lý chi phí, và Quản lý rủi ro. Phù hợp cho sinh viên và người làm việc trong lĩnh vực quản lý dự án.",
    soCau: 201,
  },
  {
    id: "mon13-1",
    monId: "mon-13",
    title: "Giải Tích 1 (PTIT) - 2025",
    description: "",
    soCau: 40,
  },
  {
    id: "mon14-1",
    monId: "mon-14",
    title: "Đề trắc nghiệm Tư tưởng Hồ Chí Minh theo chương",
    description: "Đề được tổ chức theo các chương, dễ dàng ôn tập hơn",
    soCau: 280,
  },
  {
    id: "mon15-1",
    monId: "mon-15",
    title: "AN TOÀN BẢO MẬT HỆ THỐNG THÔNG TIN (PTIT)",
    description: "",
    soCau: 596,
  },
  {
    id: "mon16-1",
    monId: "mon-16",
    title: "Xử lý Tín hiệu số (PTIT) - 2025",
    description: "",
    soCau: 41,
  },
  {
    id: "mon17-1",
    monId: "mon-17",
    title: "ATMTT 1",
    description: "",
    soCau: 38,
  },
  {
    id: "mon18-1",
    monId: "mon-18",
    title: "Triết học Mác-Lênin (PTIT) - MỚI NHẤT",
    description: "",
    soCau: 433,
  },
  {
    id: "mon19-1",
    monId: "mon-19",
    title: "Kinh Tế Chính Trị (PTIT) - MỚI NHẤT 2025",
    description: "",
    soCau: 111,
  },
  {
    id: "mon20-1",
    monId: "mon-20",
    title: "Đề thi trắc nghiệm Nguyên lý kế toán",
    description: "",
    soCau: 360,
  },
  {
    id: "mon21-1",
    monId: "mon-21",
    title: "kỹ thuật thông tin quang",
    description: "",
    soCau: 60,
  },
  {
    id: "mon22-1",
    monId: "mon-22",
    title: "tin học cơ sở",
    description: "",
    soCau: 40,
  },
  {
    id: "mon23-1",
    monId: "mon-23",
    title: "Chủ nghĩa xã hội khoa học",
    description: "",
    soCau: 348,
  },
  {
    id: "mon23-2",
    monId: "mon-23",
    title: "Chủ nghĩa Xã hội Khoa học (PTIT) Mới nhất năm 2025",
    description: "",
    soCau: 555,
  },
  {
    id: "mon24-1",
    monId: "mon-24",
    title: "Đề trắc nghiệm phương pháp luận nghiên cứu khoa học số 1",
    description: "Cứ ôn là A+",
    soCau: 1202,
  },
  {
    id: "mon25-1",
    monId: "mon-25",
    title: "Kiến trúc và Giao thức IoT",
    description: "",
    soCau: 267,
  },
  {
    id: "mon25-2",
    monId: "mon-25",
    title: "TH IoT",
    description: "",
    soCau: 48,
  },
  {
    id: "mon26-1",
    monId: "mon-26",
    title: "Đề trắc nghiệm An toàn Web và CSDL số 1",
    description: "Cứ ôn là A+",
    soCau: 170,
  },
  {
    id: "mon27-1",
    monId: "mon-27",
    title: "Kinh tế vĩ mô (PTIT)",
    description: "",
    soCau: 262,
  },
  {
    id: "mon28-1",
    monId: "mon-28",
    title: "Pháp Luật Đại Cương (PTIT) - Mới nhất 2025",
    description: "",
    soCau: 429,
  },
  {
    id: "mon29-1",
    monId: "mon-29",
    title: "Đề trắc nghiệm mạng máy tính số 1 có giải thích",
    description: "Câu hỏi và giải thích được tham khảo trên github của bạn Huy Init",
    soCau: 297,
  },
  {
    id: "mon29-2",
    monId: "mon-29",
    title: "Mạng máy tính",
    description: "",
    soCau: 136,
  },
  {
    id: "mon29-3",
    monId: "mon-29",
    title: "MMT- MÔ HÌNH OSI VÀ MÔ HÌNH TCP/IP",
    description: "",
    soCau: 69,
  },
  {
    id: "mon29-4",
    monId: "mon-29",
    title: "MMT-CÁC CÔNG CỤ MẠNG",
    description: "",
    soCau: 20,
  },
  {
    id: "mon29-5",
    monId: "mon-29",
    title: "MMT-CÁC KHÁI NIỆM CƠ BẢN",
    description: "",
    soCau: 57,
  },
  {
    id: "mon29-6",
    monId: "mon-29",
    title: "MMT-TẦNG GIAO VẬN-TẦNG MẠNG",
    description: "",
    soCau: 90,
  },
  {
    id: "mon29-7",
    monId: "mon-29",
    title: "MMT-TẦNG LIÊN KẾT DỮ LIỆU VÀ TẦNG VẬT LÝ-AN TOÀN VÀ BẢO MẬT MẠNG",
    description: "",
    soCau: 52,
  },
  {
    id: "mon30-1",
    monId: "mon-30",
    title: "Vật Lý (PTIT) - 2025",
    description: "",
    soCau: 40,
  },
  {
    id: "mon31-1",
    monId: "mon-31",
    title: "Kế toán quản trị",
    description: "",
    soCau: 104,
  },
  {
    id: "mon31-2",
    monId: "mon-31",
    title: "KTQT PTIT",
    description: "",
    soCau: 100,
  },
  {
    id: "mon31-3",
    monId: "mon-31",
    title: "trắc nghiệm KTQT",
    description: "",
    soCau: 99,
  },
  {
    id: "mon32-1",
    monId: "mon-32",
    title: "Đề trắc nghiệm lịch sử Đảng số 01",
    description: "Cứ ôn là A+",
    soCau: 100,
  },
  {
    id: "mon32-2",
    monId: "mon-32",
    title: "Đề trắc nghiệm lịch sử Đảng số 02",
    description: "Cứ ôn là A+",
    soCau: 220,
  },
  {
    id: "mon32-3",
    monId: "mon-32",
    title: "Đề trắc nghiệm lịch sử Đảng số 03",
    description: "Cứ ôn là A+",
    soCau: 70,
  },
  {
    id: "mon32-4",
    monId: "mon-32",
    title: "Đề trắc nghiệm lịch sử Đảng số 04",
    description: "Cứ ôn là A+",
    soCau: 50,
  },
  {
    id: "mon32-5",
    monId: "mon-32",
    title: "Lịch Sử Đảng - PTIT 2025",
    description: "",
    soCau: 148,
  },
  {
    id: "mon33-1",
    monId: "mon-33",
    title: "Quản trị bán hàng",
    description: "",
    soCau: 146,
  },
  {
    id: "mon34-1",
    monId: "mon-34",
    title: "Đại Số (PTIT) - 2025",
    description: "",
    soCau: 40,
  },
  {
    id: "mon35-1",
    monId: "mon-35",
    title: "Đề trắc nghiệm Pháp luật đại cương theo chương",
    description: "Đề được tổ chức theo các chương, dễ dàng ôn tập hơn",
    soCau: 470,
  },
  {
    id: "mon36-1",
    monId: "mon-36",
    title: "Lập trình nhúng",
    description: "",
    soCau: 158,
  },
  {
    id: "mon37-1",
    monId: "mon-37",
    title: "PR – Lý luận và ứng dụng",
    description: "",
    soCau: 86,
  },
  {
    id: "mon38-1",
    monId: "mon-38",
    title: "Mạng máy tính",
    description: "",
    soCau: 60,
  },
  {
    id: "mon38-2",
    monId: "mon-38",
    title: "Mạng thông tin quang",
    description: "",
    soCau: 186,
  },
];

// Moi de tai rieng khi mo: gop ca 60 de vao goi JS la bat moi nguoi tai ca chuc MB.
export const NAP_CAU_HOI: Partial<Record<string, () => Promise<CauHoi[]>>> = {
  "attt-1": () => import("./attt-1.json").then((m) => m.default as CauHoi[]),
  "attt-2": () => import("./attt-2.json").then((m) => m.default as CauHoi[]),
  "mon2-1": () => import("./mon2-1.json").then((m) => m.default as CauHoi[]),
  "mon3-1": () => import("./mon3-1.json").then((m) => m.default as CauHoi[]),
  "mon3-2": () => import("./mon3-2.json").then((m) => m.default as CauHoi[]),
  "mon3-3": () => import("./mon3-3.json").then((m) => m.default as CauHoi[]),
  "mon3-4": () => import("./mon3-4.json").then((m) => m.default as CauHoi[]),
  "mon3-5": () => import("./mon3-5.json").then((m) => m.default as CauHoi[]),
  "mon4-1": () => import("./mon4-1.json").then((m) => m.default as CauHoi[]),
  "mon5-1": () => import("./mon5-1.json").then((m) => m.default as CauHoi[]),
  "mon5-2": () => import("./mon5-2.json").then((m) => m.default as CauHoi[]),
  "mon6-1": () => import("./mon6-1.json").then((m) => m.default as CauHoi[]),
  "mon7-1": () => import("./mon7-1.json").then((m) => m.default as CauHoi[]),
  "mon7-2": () => import("./mon7-2.json").then((m) => m.default as CauHoi[]),
  "mon8-1": () => import("./mon8-1.json").then((m) => m.default as CauHoi[]),
  "mon9-1": () => import("./mon9-1.json").then((m) => m.default as CauHoi[]),
  "mon10-1": () => import("./mon10-1.json").then((m) => m.default as CauHoi[]),
  "mon11-1": () => import("./mon11-1.json").then((m) => m.default as CauHoi[]),
  "mon12-1": () => import("./mon12-1.json").then((m) => m.default as CauHoi[]),
  "mon13-1": () => import("./mon13-1.json").then((m) => m.default as CauHoi[]),
  "mon14-1": () => import("./mon14-1.json").then((m) => m.default as CauHoi[]),
  "mon15-1": () => import("./mon15-1.json").then((m) => m.default as CauHoi[]),
  "mon16-1": () => import("./mon16-1.json").then((m) => m.default as CauHoi[]),
  "mon17-1": () => import("./mon17-1.json").then((m) => m.default as CauHoi[]),
  "mon18-1": () => import("./mon18-1.json").then((m) => m.default as CauHoi[]),
  "mon19-1": () => import("./mon19-1.json").then((m) => m.default as CauHoi[]),
  "mon20-1": () => import("./mon20-1.json").then((m) => m.default as CauHoi[]),
  "mon21-1": () => import("./mon21-1.json").then((m) => m.default as CauHoi[]),
  "mon22-1": () => import("./mon22-1.json").then((m) => m.default as CauHoi[]),
  "mon23-1": () => import("./mon23-1.json").then((m) => m.default as CauHoi[]),
  "mon23-2": () => import("./mon23-2.json").then((m) => m.default as CauHoi[]),
  "mon24-1": () => import("./mon24-1.json").then((m) => m.default as CauHoi[]),
  "mon25-1": () => import("./mon25-1.json").then((m) => m.default as CauHoi[]),
  "mon25-2": () => import("./mon25-2.json").then((m) => m.default as CauHoi[]),
  "mon26-1": () => import("./mon26-1.json").then((m) => m.default as CauHoi[]),
  "mon27-1": () => import("./mon27-1.json").then((m) => m.default as CauHoi[]),
  "mon28-1": () => import("./mon28-1.json").then((m) => m.default as CauHoi[]),
  "mon29-1": () => import("./mon29-1.json").then((m) => m.default as CauHoi[]),
  "mon29-2": () => import("./mon29-2.json").then((m) => m.default as CauHoi[]),
  "mon29-3": () => import("./mon29-3.json").then((m) => m.default as CauHoi[]),
  "mon29-4": () => import("./mon29-4.json").then((m) => m.default as CauHoi[]),
  "mon29-5": () => import("./mon29-5.json").then((m) => m.default as CauHoi[]),
  "mon29-6": () => import("./mon29-6.json").then((m) => m.default as CauHoi[]),
  "mon29-7": () => import("./mon29-7.json").then((m) => m.default as CauHoi[]),
  "mon30-1": () => import("./mon30-1.json").then((m) => m.default as CauHoi[]),
  "mon31-1": () => import("./mon31-1.json").then((m) => m.default as CauHoi[]),
  "mon31-2": () => import("./mon31-2.json").then((m) => m.default as CauHoi[]),
  "mon31-3": () => import("./mon31-3.json").then((m) => m.default as CauHoi[]),
  "mon32-1": () => import("./mon32-1.json").then((m) => m.default as CauHoi[]),
  "mon32-2": () => import("./mon32-2.json").then((m) => m.default as CauHoi[]),
  "mon32-3": () => import("./mon32-3.json").then((m) => m.default as CauHoi[]),
  "mon32-4": () => import("./mon32-4.json").then((m) => m.default as CauHoi[]),
  "mon32-5": () => import("./mon32-5.json").then((m) => m.default as CauHoi[]),
  "mon33-1": () => import("./mon33-1.json").then((m) => m.default as CauHoi[]),
  "mon34-1": () => import("./mon34-1.json").then((m) => m.default as CauHoi[]),
  "mon35-1": () => import("./mon35-1.json").then((m) => m.default as CauHoi[]),
  "mon36-1": () => import("./mon36-1.json").then((m) => m.default as CauHoi[]),
  "mon37-1": () => import("./mon37-1.json").then((m) => m.default as CauHoi[]),
  "mon38-1": () => import("./mon38-1.json").then((m) => m.default as CauHoi[]),
  "mon38-2": () => import("./mon38-2.json").then((m) => m.default as CauHoi[]),
};
